### ISSUE TITLE
Laravel sample 

### ISSUE THREAD

**Issue by mrezauli** [neodynamic/WebClientPrint5PHP-Sample#1]
Want a laravel sample project for WCP5

**Comment by neodynamic** [comment]
The sample project is not always right for your dev needs and might complicate things unnecessarily. Most of the features of WebClientPrint are described in the following set of articles at [https://www.neodynamic.com/products/printing/raw-data/php/articles](https://www.neodynamic.com/products/printing/raw-data/php/articles) which include Laravel code, so please refer to them instead. Thanks,
